language: node_js

node_js: 
  - "stable"

before_install: cd api/

cache:
  directories:
    - "node_modules"

install: 
  - npm install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE mealApp;" -U postgres
  - psql -c "CREATE USER boss WITH PASSWORD null;" -U postgres
  
script:
  - npm test  

after_success:
  - npm run coverage  