language: node_js

node_js: 
  - "stable"

before_install: cd api/

cache:
  directories:
    - "node_modules"

install: 
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database mealApp;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD bosunbosun71;" -U postgres
  - npm run build  

script:
  - npm test  

after_success:
  - npm run coverage  